### ISSUE TITLE
Can't find swig when installing

### ISSUE THREAD

**Issue by bustawin** [frawau/pyhvac#2]
Looking forward to use the library :-)

When installing the library, I am having the following issue:

```shell
pip3 install pyhvac
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyhvac
  Using cached pyhvac-0.1.0.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: pyhvac
  DEPRECATION: pyhvac is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyhvac ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyhvac did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      /home/pi/repos/venvs/light/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running clone_build
      error: [Errno 2] No such file or directory: '/usr/local/bin/swig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyhvac

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

I do have swig installed (`apt-get install swig`) just not there. I see in your code that you try to uninstall swig? So I don't know much how to move forward. I hope you can help me. Thank you! :-)

**Comment by frawau** [comment]
Hi,
I am wondering what architecture you are trying to build for.

In any case, you can try on your machine
   `git clone https://github.com/frawau/pyhvac.git`
    `cd pyhvac`
   `python3 -m build`

Just tried on my Ubuntu 22.10 x86_64  and it build OK.

If the build succeeds, you can then 
`pip3 install dist/pyhvac-0.1.0-xxxx.whl`

You may want too uninstall swig and let the build process handle that.

**Comment by frawau** [comment]
You need to be able to build the library with cpp

**Comment by bustawin** [comment]
@frawau Thanks for the comment! It was an old raspberry with armv6. I tried with a newer one arm64 that had already a wheel, so it installed well :-)
Now I have the same issue as https://github.com/frawau/pyhvac/issues/1, all commands yield the same output, but we can close this one already. Thanks!
